jenkins:
  systemMessage: "Jenkins для Demo-Admink - автоматическая сборка при push в Git"
  numExecutors: 2
  mode: NORMAL
  scmCheckoutRetryCount: 3

  securityRealm:
    local:
      allowsSignup: false
      users:
        - id: "admin"
          name: "Administrator"
          password: "${JENKINS_ADMIN_PASSWORD:-admin}"

  authorizationStrategy:
    loggedInUsersCanDoAnything:
      allowAnonymousRead: false

unclassified:
  location:
    url: "http://localhost:8081/"
    adminAddress: "admin@localhost"

  gitHubPluginConfig:
    hookUrl: "http://localhost:8081/github-webhook/"

tool:
  git:
    installations:
      - name: "Default"
        home: "git"

  maven:
    installations:
      - name: "Maven 3"
        home: ""
        properties:
          - installSource:
              installers:
                - maven:
                    id: "3.9.6"

jobs:
  - script: >
      pipelineJob('demo-admink-pipeline') {
        description('Pipeline для автоматической сборки Demo-Admink')
        
        definition {
          cpsScm {
            scm {
              git {
                remote {
                  url('${GIT_REPO_URL}')
                }
                branches('*/main')
              }
            }
            scriptPath('Jenkinsfile')
          }
        }
        
        triggers {
          // Poll SCM каждые 2 минуты - для серверов без публичного доступа
          scm('H/2 * * * *')
        }
        
        properties {
          githubProjectUrl('${GIT_REPO_URL}')
        }
      }

